const products = [
    {
        name: "Birth chart",
        price: 25,
        deliverables: "Letter + PDF Document with technical specifications",
        deliveryTerm: 14,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/cartanatal.jpg?raw=true",
        category: "Astrology",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Globa1",
        duration: 0,
        language: "SPA / ENG",
        place: "N/A",
        id: "1.1"
    },
    {
        name: "Sun revolution",
        price: 20,
        deliverables: "Diagram + PDF document with technical specifications",
        deliveryTerm: 7,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/revolucionsolar.jpg?raw=true",
        category: "Astrology",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 0,
        language: "SPA / ENG",
        place: "N/A",
        id: "1.2"
    },
    {
        name: "Transits",
        price: 18,
        deliverables: "PDF Document (influence analysis)",
        deliveryTerm: 7,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/transitos.jpg?raw=true",
        category: "Astrology",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 0,
        language: "SPA / ENG",
        place: "N/A",
        id: "1.3"
    },
    {
        name: "Progressions",
        price: 18,
        deliverables: "PDF Document (risks and opportunities)",
        deliveryTerm: 7,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/progresiones.jpg?raw=true",
        category: "Astrology",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 0,
        language: "SPA / ENG",
        place: "N/A",
        id: "1.4"
    },
    {
        name: "Synastries",
        price: 20,
        deliverables: "Explanotary PDF Document + videos",
        deliveryTerm: 7,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/sinastria.jpg?raw=true",
        category: "Astrology",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 0,
        language: "SPA / ENG",
        place: "N/A",
        id: "1.5"
    },
    {
        name: "Astrological MBTI",
        price: 50,
        deliverables: "Explanotary PDF Document + videos",
        deliveryTerm: 30,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/mbti.jpg?raw=true",
        category: "Astrology",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 0,
        language: "SPA / ENG",
        place: "N/A",
        id: "1.6"
    },
    {
        name: "Dice roll 2 questions",
        price: 10,
        deliverables: "Videos + Photos + Audios",
        deliveryTerm: 1,
        quantityOfQuestions: 2,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/dados2pre.jpg?raw=true",
        category: "DiceAndRunes",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 0,
        language: "SPA / ENG",
        place: "N/A",
        id: "2.1"
    },
    {
        name: "Dice roll 3 questions",
        price: 13,
        deliverables: "Videos + Photos + Audios",
        deliveryTerm: 1,
        quantityOfQuestions: 3,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/dados3pre.jpg?raw=true",
        category: "DiceAndRunes",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 0,
        language: "SPA / ENG",
        place: "N/A",
        id: "2.2"
    },
    {
        name: "Dice roll 4 questions",
        price: 15,
        deliverables: "Videos + Photos + Audios",
        deliveryTerm: 1,
        quantityOfQuestions: 4,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/dados4pre.jpg?raw=true",
        category: "DiceAndRunes",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 0,
        language: "SPA / ENG",
        place: "N/A",
        id: "2.3"
    },
    {
        name: "Runes roll 2 questions",
        price: 10,
        deliverables: "Videos + Photos + Audios",
        deliveryTerm: 1,
        quantityOfQuestions: 2,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/runas2pre.jpg?raw=true",
        category: "DiceAndRunes",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 0,
        language: "SPA / ENG",
        place: "N/A",
        id: "2.4"
    },
    {
        name: "Runes roll 3 questions",
        price: 13,
        deliverables: "Videos + Photos + Audios",
        deliveryTerm: 1,
        quantityOfQuestions: 3,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/runas3pre.jpg?raw=true",
        category: "DiceAndRunes",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 0,
        language: "SPA / ENG",
        place: "N/A",
        id: "2.5"
    },
    {
        name: "Runes roll 4 questions",
        price: 15,
        deliverables: "Videos + Photos + Audios",
        deliveryTerm: 1,
        quantityOfQuestions: 4,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/runas4pre.jpg?raw=true",
        category: "DiceAndRunes",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 0,
        language: "SPA / ENG",
        place: "N/A",
        id: "2.6"
    },
    {
        name: "Night of wine and tarot",
        price: 20,
        deliverables: "N/A",
        deliveryTerm: 0,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/vinotarot.jpg?raw=true",
        category: "Event",
        date: "25/03/2023",
        time: 19,
        ticketsAvailable: 50,
        stock: 0,
        deliverableZone: "N/A",
        duration: 0,
        language: "SPA / ENG",
        description: "A meeting with tarot and wine",
        place: "Bilbao",
        id: "3.1"
    },
    {
        name: "Female mythologies",
        price: 20,
        deliverables: "N/A",
        deliveryTerm: 0,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/mitologiafemenina.jpg?raw=true",
        category: "Event",
        date: "28/04/2023",
        time: 18,
        ticketsAvailable: 50,
        stock: 0,
        deliverableZone: "N/A",
        duration: 0,
        language: "SPA / ENG",
        description: "A meeting to deepen women in mythologies",
        place: "Bilbao",
        id: "3.2"
    },
    {
        name: "Astrological symbols evenings",
        price: 20,
        deliverables: "N/A",
        deliveryTerm: 0,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/tardesimbolos.jpg?raw=true",
        category: "Event",
        date: "05/05/2023",
        time: 18,
        ticketsAvailable: 50,
        stock: 0,
        deliverableZone: "N/A",
        duration: 0,
        language: "SPA / ENG",
        description: "Evenings to deepen astrological symbols",
        place: "Bilbao",
        id: "3.3"
    },
    {
        name: "Chocolate, wine, and tarot",
        price: 20,
        deliverables: "N/A",
        deliveryTerm: 0,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/chocolatevino.jpg?raw=true",
        category: "Event",
        date: "13/06/2023",
        time: 19,
        ticketsAvailable: 50,
        stock: 0,
        deliverableZone: "N/A",
        duration: 0,
        language: "SPA / ENG",
        description: "Sunsets with chocolate, good wine and astrology",
        place: "Bilbao",
        id: "3.4"
    },
    {
        name: "Runes, dice, women, and more",
        price: 20,
        deliverables: "N/A",
        deliveryTerm: 0,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/tarotrunas.jpg?raw=true",
        category: "Event",
        date: "24/07/2023",
        time: 18,
        ticketsAvailable: 50,
        stock: 0,
        deliverableZone: "N/A",
        duration: 0,
        language: "SPA / ENG",
        description: "An afternoon to spend between us with the mystery of dice and runes",
        place: "Bilbao",
        id: "3.5"
    },
    {
        name: "Awakening the feminine force",
        price: 150,
        deliverables: "N/A",
        deliveryTerm: 0,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/retiromujeres.jpg?raw=true",
        category: "Event",
        date: "15/08/2023",
        time: 8,
        ticketsAvailable: 50,
        stock: 0,
        deliverableZone: "N/A",
        duration: 0,
        language: "SPA / ENG",
        description: "Women's Holistic Retreat Weekend",
        place: "Bilbao",
        id: "3.6"
    },
    {
        name: "Tarot deck",
        price: 20,
        deliverables: "Tarot deck",
        deliveryTerm: 14,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/decktarot.jpg?raw=true",
        category: "Products",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 15,
        deliverableZone: "Global",
        duration: 0,
        language: "SPA / ENG",
        description: "Personalised tarot deck",
        place: "N/A",
        id: "4.1"
    },
    {
        name: "Stones set",
        price: 20,
        deliverables: "Set of 5 stones",
        deliveryTerm: 14,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/piedrasenergeticas.jpg?raw=true",
        category: "Products",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 21,
        deliverableZone: "Global",
        duration: 0,
        language: "SPA / ENG",
        description: "Set of 5 stones selected by the buyer",
        place: "N/A",
        id: "4.2"
    },
    {
        name: "Nordic runes",
        price: 28,
        deliverables: "A deck of nordic runes",
        deliveryTerm: 14,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/runasnordicas.jpg?raw=true",
        category: "Products",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 15,
        deliverableZone: "Global",
        duration: 0,
        language: "N/A",
        description: "A deck of nordic runes",
        place: "N/A",
        id: "4.3"
    },
    {
        name: "Scented candle",
        price: 7,
        deliverables: "A scented candle 20X15cms",
        deliveryTerm: 5,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/velasaromatizantes.jpg?raw=true",
        category: "Products",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 10,
        deliverableZone: "Bizkaia",
        duration: 0,
        language: "N/A",
        description: "A scented candle 20X15cms (mint, wood, lemon, vanilla)",
        place: "N/A",
        id: "4.4"
    },
    {
        name: "Dices for rolling",
        price: 7,
        deliverables: "A set of 3 polyedric dices (20 faces)",
        deliveryTerm: 5,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/dadostiradas.jpg?raw=true",
        category: "Products",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 10,
        deliverableZone: "Global",
        duration: 0,
        language: "N/A",
        description: "A set of 3 polyedric dices (20 faces) (green, blue, red, violet, yellow, orange)",
        place: "N/A",
        id: "4.5"
    },
    {
        name: "Incense stick",
        price: 2,
        deliverables: "An incense stick of 20x5cms",
        deliveryTerm: 5,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/sahumerio.jpg?raw=true",
        category: "Products",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 20,
        deliverableZone: "Bizkaia",
        duration: 0,
        language: "N/A",
        description: "An incense stick of 20x5cms (a mixture of smells)",
        place: "N/A",
        id: "4.6"
    },
    {
        name: "Introduction to Tarot",
        price: 25,
        deliverables: "N/A",
        deliveryTerm: 0,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/introastro.jpg?raw=true",
        category: "Workshops",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 60,
        language: "SPA / ENG",
        description: "N/A",
        place: "N/A",
        id: "5.1"
    },
    {
        name: "Medium Tarot level",
        price: 35,
        deliverables: "N/A",
        deliveryTerm: 0,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/astromedio.jpg?raw=true",
        category: "Workshops",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 60,
        language: "SPA / ENG",
        description: "N/A",
        place: "N/A",
        id: "5.2"
    },
    {
        name: "Advanced Tarot level",
        price: 50,
        deliverables: "N/A",
        deliveryTerm: 0,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/astroavanzado.jpg?raw=true",
        category: "Workshops",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 60,
        language: "SPA / ENG",
        description: "N/A",
        place: "N/A",
        id: "5.3"
    },
    {
        name: "Introduction to Astrology",
        price: 25,
        deliverables: "N/A",
        deliveryTerm: 0,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/introtarot.jpg?raw=true",
        category: "Workshops",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 60,
        language: "SPA / ENG",
        description: "N/A",
        place: "N/A",
        id: "5.4"
    },
    {
        name: "Medium Astrology level",
        price: 35,
        deliverables: "N/A",
        deliveryTerm: 0,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/tarotmedionivel.jpg?raw=true",
        category: "Workshops",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 60,
        language: "SPA / ENG",
        description: "N/A",
        place: "N/A",
        id: "5.5"
    },
    {
        name: "Advanced Astrology level",
        price: 50,
        deliverables: "N/A",
        deliveryTerm: 0,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/tarotavanzado.jpg?raw=true",
        category: "Workshops",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 60,
        language: "SPA / ENG",
        description: "N/A",
        place: "N/A",
        id: "5.6"
    },
    {
        name: "Astrological Houses",
        price: 25,
        deliverables: "Videos + Photos + Audios",
        deliveryTerm: 7,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/casasastrologicas.jpg?raw=true",
        category: "Tarot",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 0,
        language: "SPA / ENG",
        description: "N/A",
        place: "N/A",
        id: "6.1"
    },
    {
        name: "Pyramid spread (Tarot)",
        price: 30,
        deliverables: "Videos + Photos + Audios",
        deliveryTerm: 7,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/introtarot.jpg?raw=true",
        category: "Tarot",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 0,
        language: "SPA / ENG",
        description: "N/A",
        place: "N/A",
        id: "6.2"
    },
    {
        name: "Tarot 2 questions",
        price: 15,
        deliverables: "Videos + Photos + Audios",
        deliveryTerm: 7,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/tarottrespreguntas.jpg?raw=true",
        category: "Tarot",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 0,
        language: "SPA / ENG",
        description: "N/A",
        place: "N/A",
        id: "6.3"
        },
        {
        name: "Tarot 3 questions",
        price: 20,
        deliverables: "Videos + Photos + Audios",
        deliveryTerm: 7,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/tarotdospreguntas.jpg?raw=true",
        category: "Tarot",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 0,
        language: "SPA / ENG",
        description: "N/A",
        place: "N/A",
        id: "6.4"
        },
        {
        name: "Tarot 4 questions",
        price: 25,
        deliverables: "Videos + Photos + Audios",
        deliveryTerm: 7,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/tarotcuatropreguntas.jpg?raw=true",
        category: "Tarot",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 0,
        language: "SPA / ENG",
        description: "N/A",
        place: "N/A",
        id: "6.5"
        },
    {
        name: "1 hour of Tarot",
        price: 30,
        deliverables: "Videos + Photos + Audios",
        deliveryTerm: 7,
        quantityOfQuestions: 0,
        image: "https://github.com/lucianobizin/project-js/blob/main/img/tarotunahora.jpg?raw=true",
        category: "Tarot",
        date: "01/01/01",
        time: 0,
        ticketsAvailable: 0,
        stock: 0,
        deliverableZone: "Global",
        duration: 0,
        language: "SPA / ENG",
        description: "N/A",
        place: "N/A",
        id: "6.6"
    }
]


export const getProducts = () => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(products);
        }, 200);
    });
};

export const getProductByCategory = (idCategory) => {
    return new Promise(resolve => {
        setTimeout(() => {
            const productCategory = products.filter(prod => prod.category === idCategory)
            resolve(productCategory);
        }, 100)
    })
}

export const getOneProduct = (id) => {
    return new Promise(resolve => {
        setTimeout(() => {
            const product = products.find(prod => prod.id === id);
            resolve(product);
        }, 200)
    })
}